#!/bin/sh

# This script uses inotifywait to execute a command when something changes in
# the filesystem. 

# This script accepts two parameters. The second is optional.

# The first parameter is the file to watch. If the second parameter is unset,
# then the first parameter is also the command that is executed in response to
# the signal from inotify.

# The second parameter, if set, is the command that is executed when inotify
# reports a filesystem event on the first parameter.

# Add -r to the inotifywait options if the watched file is a directory. 

# Usage:
# inotifyrun $file_to_watch $file_to_execute[optional]

# Example, to make a remote copy of a file each time it changes:
# inotifyrun ~/my_file rsync myfile user@remote.host:~/my_file

# man inotifywait for more info

test ! $(command -v inotifywait) \
	&& { printf "inotifywait: command not found\n" ; exit 1 ; }

while true; do
	inotifywait -e close_write "$1"
	if [ -z $2 ]; then
		"$@"
	else
		# This must be in a subshell or shift will eat one parameter on
	        # each run 
		(
		shift
		"$@"
		)
	fi
done
